const mockSliderContent = [
	{
		path: 'yoga3.jpg',
		create: 'May 2, 2018 by',
		author: 'Letizia Biafore',
		headWord: 'Yoga',
		description: 'best ways to sneak yoga into your holiday',
		tags: 'Lifestyle, yoga, travel',
	},
	{
		path: 'healthy.jpg',
		create: 'September 15, 2020 by',
		author: 'John Doe',
		headWord: 'Healthy',
		description: 'tips for maintaining a healthy diet',
		tags: 'Health, nutrition, lifestyle',
	},
	{
		path: 'hiking.avif',
		create: 'March 10, 2019 by',
		author: 'Alice Smith',
		headWord: 'Hiking',
		description: 'exploring nature on foot in regions',
		tags: 'Travel, adventure, hiking',
	},
	{
		path: 'travel-tips.jpg',
		create: 'June 5, 2020 by',
		author: 'David Johnson',
		headWord: 'Travel',
		description: 'useful tips for planning your next trip',
		tags: 'Travel, tips, vacation',
	},
	{
		path: 'gardening-ideas.jpg',
		create: 'October 12, 2022 by',
		author: 'Sophia Anderson',
		headWord: 'Gardening',
		description: 'creative ideas for your space',
		tags: 'Gardening, ideas, plants',
	},
	{
		path: 'cooking-recipes.webp',
		create: 'January 18, 2021 by',
		author: 'Sarah Williams',
		headWord: 'Cooking',
		description: 'delicious recipes for your culinary',
		tags: 'Food, recipes, cooking',
	},
	{
		path: 'fitness.webp',
		create: 'August 30, 2020 by',
		author: 'Michael Brown',
		headWord: 'Fitness',
		description: 'effective workouts for a lifestyle',
		tags: 'Fitness, health, exercise',
	},
	{
		path: 'artistic.jpg',
		create: 'December 5, 2019 by',
		author: 'Emily Davis',
		headWord: 'Creations',
		description: 'inspiring art creations from the world',
		tags: 'Art, creativity, inspiration',
	},
	{
		path: 'music.jpg',
		create: 'May 20, 2021 by',
		author: 'James Wilson',
		headWord: 'Music',
		description: 'discover new music to add to playlist',
		tags: 'Music, recommendations, playlist',
	},
];

export default mockSliderContent;
